### ISSUE TITLE
Simple composed sender compiles with thread_scheduler but not time_scheduler

### ISSUE THREAD

**Issue by jefftrull** [intel/cpp-baremetal-senders-and-receivers#167]
I made a simple example to try out the library, consisting of two `just_result_of`'s followed by a `when_all` and a `then`. It compiles and runs when `thread_scheduler` is used but fails to compile with `time_scheduler`.

The compile error is large and complex but in the end comes down to a tuple index out of range, which I didn't know how to debug.

Reduced example (will compile but not run if fixed because I left out the timer implementation):

```c++
#include <async/schedulers/thread_scheduler.hpp>
#include <async/schedulers/time_scheduler.hpp>
#include <async/schedulers/timer_manager.hpp>
#include <async/just.hpp>
#include <async/just_result_of.hpp>
#include <async/start_detached.hpp>
#include <async/start_on.hpp>
#include <async/sync_wait.hpp>
#include <async/then.hpp>
#include <async/when_all.hpp>

#include <chrono>
#include <iostream>

//
// BOILERPLATE FROM THE DOCS
// for timer_scheduler. Will not link, just for compilation
//

// provide a HAL for the timer scheduler

namespace {
// A HAL defines a time_point type and a task type,
// and provides functions to control a timer interrupt
struct asio_hal {
    using time_point_t = std::chrono::steady_clock::time_point;
    using task_t = async::timer_task<time_point_t>;

    static auto enable() -> void;
    static auto disable() -> void;
    static auto set_event_time(time_point_t tp) -> void;
    static auto now() -> time_point_t;
};

// use the generic timer manager
using timer_manager_t = async::generic_timer_manager<asio_hal>;
} // namespace

// tell the library how to infer a time point type from a duration type by
// specializing time_point_for
template <typename Rep, typename Period>
struct async::timer_mgr::time_point_for<std::chrono::duration<Rep, Period>> {
    using type = asio_hal::time_point_t;
};

// time_scheduler will use this timer_manager
template <> inline auto async::injected_timer_manager<> = timer_manager_t{};

int main() {
    using namespace std::literals;
    using namespace async;

    auto s0 = start_on(time_scheduler{4s},
//    auto s0 = start_on(thread_scheduler{},   // compiles
                       async::just_result_of([](){ return 42; }));
    auto s1 = start_on(time_scheduler{6s},
//    auto s1 = start_on(thread_scheduler{},   // compiles
                       async::just_result_of([](){ return 13; }));
    auto combined = then(when_all(s0, s1), [](int a, int b){ return a*b; });
    
    auto result = sync_wait(combined).value();   // 42*13, delivered shortly after 6s when s1 completes

    std::cout << stdx::get<0>(result) << "\n";

}

```

**Comment by elbeno** [comment]
Smaller example:
```cpp
auto s0 = just(42);
auto s1 = start_on(time_scheduler{1s}, just());
auto combined = when_all(s0, s1) | then([](int a) { return a; });
auto op = connect(combined, universal_receiver{});
```
For me this compiles with GCC 14.2; not with clang 20.1.5.

**Comment by elbeno** [comment]
If the `int` comes from `s1` rather than `s0`, it compiles:
```cpp
auto s0 = just();
auto s1 = start_on(time_scheduler{1s}, just(42));
auto combined = when_all(s0, s1) | then([](int a) { return a; });
auto op = connect(combined, universal_receiver{});
```

**Comment by jefftrull** [comment]
Thanks for the quick response! It does look like my original testcase is failing, but for a different reason this time:

```
include/async/env.hpp:56:33: error: member ‘stdx::v1::detail::element<1, const async::env<>&>::value’ is uninitialized reference
```

**Comment by elbeno** [comment]
OK thanks, with the latest update to that PR I think that issue is also fixed.
